# Exception handling
A method to stop the program from crashing after an error.

### example
```py
try:  
  print(x)  
except:  
  print("An exception occurred")
```

### notes
When an error occurs, an "exception" is thrown. This could be caused by using the wrong data type, attemping to divide by 0 or attempting to access a non-existent element in an array to name a few examples.

Once the exception is thrown, the computer has to handle the exception to avoid crashing. It does this by pasuing execution of the program and saving the current [[volitile]] state of the program on the system stack befroe running a section of code called a catch block.

This code will prevent the program from crashing and migh inform the user that an error has occured. Once the exception has been handled, the program uses the system stack to resore its previous state before resuming execution.